'use client';
import { useState } from 'react';

type Item = { id: string; status: string; priority: string; dueAt?: string; syncStatus: string; syncError?: string; steps: Array<{ id: string; title: string; status: string; due_at?: string }>; events: Array<{ id: string; event_type: string; created_at: string }> };
export function ActionDetail({ item, readOnly = false }: { item: Item; readOnly?: boolean }) {
  const [busy, setBusy] = useState(''); const [error, setError] = useState('');
  const call = async (url: string, method: string, body?: unknown) => { setBusy(url); setError(''); try { const response = await fetch(url, { method, headers: { 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload.error || 'Request failed'); window.location.reload(); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Request failed'); setBusy(''); } };
  return <div className="detail-grid" style={{ marginTop: 28 }}><section className="panel">{readOnly && <p className="muted">Read-only household access</p>}<div className="toolbar"><select disabled={readOnly || !!busy} className="field" style={{ width: 170 }} value={item.status} onChange={(event) => call(`/api/actions/${item.id}`, 'PATCH', { status: event.target.value })}><option>open</option><option>waiting</option><option>done</option><option>dismissed</option></select><button className="button" disabled={readOnly || !!busy} onClick={() => call(`/api/actions/${item.id}/sync`, 'POST')}>Push to Paperless</button><button className="button" disabled={readOnly || !!busy} onClick={() => call(`/api/actions/${item.id}/sync?direction=pull`, 'POST')}>Pull changes</button></div>
    <h2>Steps</h2><div className="steps">{item.steps.map((step) => <button disabled={readOnly || !!busy} key={step.id} className={`step ${step.status}`} style={{ background: 'none', border: 0, color: 'inherit', textAlign: 'left', cursor: readOnly ? 'default' : 'pointer' }} onClick={() => call(`/api/actions/${item.id}/steps/${step.id}`, 'PATCH', { status: step.status === 'done' ? 'open' : 'done' })}><span>{step.status === 'done' ? '✓' : '○'}</span><span>{step.title}</span></button>)}</div>
    {!readOnly && <form className="toolbar" style={{ marginTop: 14 }} onSubmit={(event) => { event.preventDefault(); const data = new FormData(event.currentTarget); void call(`/api/actions/${item.id}/steps`, 'POST', { title: data.get('title') }); }}><input className="field" name="title" placeholder="Add a step…" required /><button className="button" disabled={!!busy}>Add</button></form>}{error && <div className="error">{error}</div>}</section>
    <aside className="panel"><h2>Sync</h2><p className="muted">Status: {item.syncStatus}</p>{item.syncError && <p className="error">{item.syncError}</p>}<h2 style={{ marginTop: 24 }}>Activity</h2>{item.events.slice(0, 12).map((event) => <p key={event.id} className="muted" style={{ fontSize: 12 }}>{event.event_type}<br />{new Date(event.created_at).toLocaleString()}</p>)}</aside></div>;
}
