'use client';
import { FormEvent, useEffect, useRef, useState } from 'react';
import { DefaultChatTransport, type UIMessage } from 'ai';
import { useChat } from '@ai-sdk/react';
import { Message, MessageContent, MessageResponse } from '@/components/ai-elements/message';

type Approval = { id: string; action_type: string; payload: Record<string, unknown>; status: string };
const welcome: UIMessage = { id: 'welcome', role: 'assistant', parts: [{ type: 'text', text: 'What should we take care of? I can find documents, explain obligations, and prepare actions for your approval.' }] };

export function Companion({ sessionId, initialMessages, initialApprovals, canApprove }: { sessionId: string; initialMessages: UIMessage[]; initialApprovals: Approval[]; canApprove: boolean }) {
  const [approvals, setApprovals] = useState(initialApprovals); const [input, setInput] = useState(''); const [decisionError, setDecisionError] = useState(''); const [decisionBusy, setDecisionBusy] = useState(''); const endRef = useRef<HTMLDivElement>(null);
  const { messages, sendMessage, status, error } = useChat({ id: sessionId, messages: initialMessages.length ? initialMessages : [welcome], transport: new DefaultChatTransport({ api: '/api/companion', body: { sessionId } }) });
  useEffect(() => endRef.current?.scrollIntoView({ behavior: 'smooth' }), [messages]);
  const refreshApprovals = async () => { try { const response = await fetch('/api/approvals'); if (!response.ok) throw new Error('Could not refresh approvals'); setApprovals((await response.json()).approvals); } catch (cause) { setDecisionError(cause instanceof Error ? cause.message : 'Could not refresh approvals'); } };
  useEffect(() => { if (status === 'ready') void refreshApprovals(); }, [status]);
  const submit = (event: FormEvent) => { event.preventDefault(); const text = input.trim(); if (!text || status !== 'ready') return; setInput(''); void sendMessage({ text }); };
  const decide = async (id: string, decision: 'approved' | 'rejected') => { setDecisionError(''); setDecisionBusy(id); try { const response = await fetch(`/api/approvals/${id}`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ decision }) }); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.error || 'Could not decide approval'); await refreshApprovals(); } catch (cause) { setDecisionError(cause instanceof Error ? cause.message : 'Could not decide approval'); } finally { setDecisionBusy(''); } };
  return <div className="split"><section className="panel chat"><div className="messages" aria-live="polite">{messages.map((message) => <Message key={message.id} from={message.role}><MessageContent>{message.parts.map((part, index) => part.type === 'text' ? (message.role === 'assistant' ? <MessageResponse key={index}>{part.text}</MessageResponse> : <span key={index}>{part.text}</span>) : null)}</MessageContent></Message>)}<div ref={endRef} /></div>
    <form className="composer" onSubmit={submit}><textarea className="field" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Ask about a document or deadline…" aria-label="Message" /><button className="button primary" disabled={status !== 'ready' || !input.trim()}>{status === 'streaming' || status === 'submitted' ? 'Thinking…' : 'Send'}</button></form>{(error || decisionError) && <div className="error" style={{ padding: '0 14px 12px' }}>{error?.message || decisionError}</div>}</section>
    <aside className="approvals"><h2>Needs approval</h2><p className="muted">AI can prepare. An owner or adult executes.</p>{approvals.map((approval) => <article className="approval" key={approval.id}><span className="pill suggested">proposal</span><h3>{approval.action_type === 'action.create' ? String(approval.payload.title || 'New action') : approval.action_type}</h3><p>{approval.action_type} · {approval.payload.paperlessDocumentId ? `Document #${approval.payload.paperlessDocumentId}` : 'Review details before approving.'}</p>{canApprove ? <div className="approval-actions"><button type="button" className="button primary" disabled={!!decisionBusy} onClick={() => decide(approval.id, 'approved')}>Approve</button><button type="button" className="button danger" disabled={!!decisionBusy} onClick={() => decide(approval.id, 'rejected')}>Reject</button></div> : <p className="muted">Your role cannot decide this proposal.</p>}</article>)}{!approvals.length && <div className="empty" style={{ padding: 24 }}>Nothing pending</div>}</aside>
  </div>;
}
